language: python
cache: pip
python:
- '3.6'
install:
  - git fetch --tags --depth=500
  - pip install 'pytest>=3.6' --force-reinstall
  - pip install pytest-cov codecov
  - pip install -r ./requirements.txt
script:
- pytest  tests/ --cov-report term --cov=./zvt --ignore=tests/recorders/
after_success:
  - codecov
deploy:
  provider: pypi
  user: foolcage
  password:
    secure: MvVCnUZUuTYxzs8R8kWTocOqZt2MGUX/W1hdKMxKJ9G9hFOYhzjEnbsF1Sc9yHB/0S1OY49068ScbN6iCuyKK2LZy/x3o7cKJgPnQt2LEjy6Yuu9MLxT6v8hJ0MTT3YCn0N8bNv4tOz7KkxxbZ8O/b5MgIKfdjBhVHEj92hhykYzyzlmG8mF+nxU/j0IGCAdxN9+IDioMIvCgnFqQhvkDwva4YbG6Uy+8YMVHFT3I+tSZRSmYxl/IwHJS+5tinI4TxX/ewrI5EznOe0HZvhF+eez+tGenS3pKF4hqF6t4RmKQX2kkdMuPFAvuveoMnPGiaSdoEMni1JPFnZL+3R4GVJPzk4F10v6AZPd10CARXqEwP23JCKAe0WvnbSBkV4iKpkvgxqPA59UwNQ90Jn4pDcTSao1WfRliAnBWCVj7S4x6xjEoNKPvOhXP3RPIYhgEFu4Ma4Cpihkof6VVtlg8VAJKH7j1vWmms3ShdddKXMeF2365sn5Owe671okYmMYMas/v47Y2Cz/0hwpVLuklNR5OYayXMXfUMIG2pH1pEFvg7y8v7ivy1EyCKGva+M/qEnoR1VGWNGSkypJHxG+w8dbtYwf3EYTA9fk/di3ygzepV7RrKJSDf8R+NwFrSfXeoEP07LonbtGN9iIz7Lp5PoB6rv99NHihlB47n1+PtM=
  on:
    tags: true
notifications:
  email:
    recipients:
    - 5533061@qq.com
env:
  matrix:
  - secure: G9oTTNGXdfP3QFJPZrSvp7zWV/DC3JJn3N8FZ+SgKuair0ThHHCG5bfBQkkgn8/HbF+AEMnEUKrQwBy1iXbOPaqBRBOG25sL9Gx6LjvUY9hnM+5zYQ/TsIthSXDNQFQhWH58tJP/1M12SkOvRcsjSurhD/As/cT8jiSgjBi0qtdtVFWBiiaVePhBch0MR9FiNnUKfOkkadMUr87H2OsklYNdiDWRPBZUjDMg9Im1UKT0BYAKCZHvg5Rgk8LC83YMf8HDLtzyNwrPVdwI4+p2i784gqk+rcWj8pePydP7abxcg9HhzJEpgwKibgbWWaV1ICML5bgcb8lgRI4eo3Qa8PUmOZG0KwwhBT8tIzxV6aNzWY61uV17PozWIwCAFTygQakQsVqpfrXrgU8h+gQYPFQ821Kf1MO9Ce6faFx0JRfCiNRTQ0jr1b8LESct1xZalWOuOJ1+w+k0OxpDCYfjVlsX13hwbVuZKBv8eKfYt+9iSjF/7sQnEA57jCUBqZBqAHCTySRGMRZBusumMDkvOxfa4exf3mVCD2uREkk0H8JlC511SpWpYlIFvhMZ52DEht0tH6lDHfI8z9ud4JLR3qRz6yH1ptZelN3nwT20/LV3k045gswC2UNNujwHxvlcaYcY0PWbCRQUxXkCkDL48PbsiKKD+26u+Y+uaYB20Vo=
